### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by vpegasus** [microsoft/visual-chatgpt#2]
```bash
Initializing VisualChatGPT
Initializing StableDiffusionInpaint to cuda:6
Downloading (…)rocessor_config.json: 100%|█████████████████████████████████████████████████████████████████████████████| 380/380 [00:00<00:00, 92.4kB/s]
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████| 974/974 [00:00<00:00, 276kB/s]
Downloading (…)olve/main/vocab.json: 100%|█████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 1.35MB/s]
Downloading (…)olve/main/merges.txt: 100%|████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 840kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<00:00, 179kB/s]
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████████████████| 4.73k/4.73k [00:00<00:00, 1.21MB/s]
Downloading (…)"pytorch_model.bin";: 100%|████████████████████████████████████████████████████████████████████████████| 603M/603M [00:02<00:00, 213MB/s]
/home/mawenjia/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/mawenjia/visual-chatgpt/visual_chatgpt.py:940 in <module>                                  │
│                                                                                                  │
│   937 │   │   return state, state, txt + ' ' + image_filename + ' '                              │
│   938                                                                                            │
│   939 if __name__ == '__main__':                                                                 │
│ ❱ 940 │   bot = ConversationBot()                                                                │
│   941 │   with gr.Blocks(css="#chatbot .overflow-y-auto{height:500px}") as demo:                 │
│   942 │   │   chatbot = gr.Chatbot(elem_id="chatbot", label="Visual ChatGPT")                    │
│   943 │   │   state = gr.State([])                                                               │
│                                                                                                  │
│ /home/mawenjia/visual-chatgpt/visual_chatgpt.py:804 in __init__                                  │
│                                                                                                  │
│   801 │   def __init__(self):                                                                    │
│   802 │   │   print("Initializing VisualChatGPT")                                                │
│   803 │   │   self.llm = OpenAI(temperature=0)                                                   │
│ ❱ 804 │   │   self.edit = ImageEditing(device="cuda:6")                                          │
│   805 │   │   self.i2t = ImageCaptioning(device="cuda:4")                                        │
│   806 │   │   self.t2i = T2I(device="cuda:1")                                                    │
│   807 │   │   self.image2canny = image2canny()                                                   │
│                                                                                                  │
│ /home/mawenjia/visual-chatgpt/visual_chatgpt.py:151 in __init__                                  │
│                                                                                                  │
│   148 │   def __init__(self, device):                                                            │
│   149 │   │   print("Initializing StableDiffusionInpaint to %s" % device)                        │
│   150 │   │   self.device = device                                                               │
│ ❱ 151 │   │   self.mask_former = MaskFormer(device=self.device)                                  │
│   152 │   │   self.inpainting = StableDiffusionInpaintPipeline.from_pretrained(        "runway   │
│   153 │                                                                                          │
│   154 │   def remove_part_of_image(self, input):                                                 │
│                                                                                                  │
│ /home/mawenjia/visual-chatgpt/visual_chatgpt.py:123 in __init__                                  │
│                                                                                                  │
│   120 │   def __init__(self, device):                                                            │
│   121 │   │   self.device = device                                                               │
│   122 │   │   self.processor = CLIPSegProcessor.from_pretrained("CIDAS/clipseg-rd64-refined")    │
│ ❱ 123 │   │   self.model = CLIPSegForImageSegmentation.from_pretrained("CIDAS/clipseg-rd64-ref   │
│   124 │                                                                                          │
│   125 │   def inference(self, image_path, text):                                                 │
│   126 │   │   threshold = 0.5                                                                    │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:1749 in to      │
│                                                                                                  │
│   1746 │   │   │   │   " model has already been set to the correct devices and casted to the co  │
│   1747 │   │   │   )                                                                             │
│   1748 │   │   else:                                                                             │
│ ❱ 1749 │   │   │   return super().to(*args, **kwargs)                                            │
│   1750 │                                                                                         │
│   1751 │   def half(self, *args):                                                                │
│   1752 │   │   # Checks if the model has been loaded in 8-bit                                    │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:927 in to           │
│                                                                                                  │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│    925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│    926 │   │                                                                                     │
│ ❱  927 │   │   return self._apply(convert)                                                       │
│    928 │                                                                                         │
│    929 │   def register_backward_hook(                                                           │
│    930 │   │   self, hook: Callable[['Module', _grad_t, _grad_t], Union[None, Tensor]]           │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in _apply       │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in _apply       │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in _apply       │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in _apply       │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:602 in _apply       │
│                                                                                                  │
│    599 │   │   │   # track autograd history of `param_applied`, so we have to use                │
│    600 │   │   │   # `with torch.no_grad():`                                                     │
│    601 │   │   │   with torch.no_grad():                                                         │
│ ❱  602 │   │   │   │   param_applied = fn(param)                                                 │
│    603 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)       │
│    604 │   │   │   if should_use_set_data:                                                       │
│    605 │   │   │   │   param.data = param_applied                                                │
│                                                                                                  │
│ /home/mawenjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:925 in convert      │
│                                                                                                  │
│    922 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):                       │
│    923 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() els  │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│ ❱  925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│    926 │   │                                                                                     │
│    927 │   │   return self._apply(convert)                                                       │
│    928                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

how to fix?

**Comment by guidongnan** [comment]
In my case, where I use 1 $\times$ A100 80GB，I replace all of the `cuda:x` in `ConversationBot.__init__()` with `cuda:0` and it works, it seems to finally use 60~70GB GPU memory.

**Comment by vpegasus** [comment]
> In my case, where I use 1 × A100 80GB，I replace all of the `cuda:x` in `ConversationBot.__init__()` with `cuda:0` and it works, it seems to finally use 60~70GB GPU memory.

yes, i read code and found it need multi-gpus

**Comment by hjbiao09** [comment]
> In my case, where I use 1 × A100 80GB，I replace all of the `cuda:x` in `ConversationBot.__init__()` with `cuda:0` and it works, it seems to finally use 60~70GB GPU memory.

Yeah, it would be helpful if the authors could provide information on the GPU memory usage of each VFM module.

**Comment by jxtps** [comment]
How did you work around the 
```
/home/mawenjia/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```
which leads to a later cuda exception when actually running? 

I tried installing pytorch with cuda 11.3 (from https://pytorch.org/get-started/previous-versions/ ): 
```
# CUDA 11.3
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
```
but that led to a cascade of package issues with `chardet` and `cchardet`. 

I also tried adding `cudatoolkit==11.3` to requirements.txt, but then get: 
```
(visgpt) jxtps@amd-delta:/mnt/usr/visual-chatgpt$ pip install -r requirement.txt
Collecting torch==1.12.1
  Using cached torch-1.12.1-cp38-cp38-manylinux1_x86_64.whl (776.3 MB)
Collecting torchvision==0.13.1
  Using cached torchvision-0.13.1-cp38-cp38-manylinux1_x86_64.whl (19.1 MB)
ERROR: Could not find a version that satisfies the requirement cudatoolkit==11.3 (from versions: none)
ERROR: No matching distribution found for cudatoolkit==11.3
```

???

**Comment by jxtps** [comment]
I got it to work by wiping my conda virtual env and then restarting with: 
```
```

**Comment by jxtps** [comment]
I got it to work by wiping my conda virtual env and restarting doing: 
```
# create a new environment
conda create -n visgpt python=3.8

# activate the new environment
conda activate visgpt

#  prepare the basic environments
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
pip install -r requirement.txt  # Edited to comment out the first two lines with torch & torchvision, may or may not be necessary

# download the visual foundation models
bash download.sh

# prepare your private openAI private key
export OPENAI_API_KEY={Your_Private_Openai_Key}

# create a folder to save images
mkdir ./image

# Start Visual ChatGPT !
python visual_chatgpt.py
```

**Comment by leosh64** [comment]
> I got it to work by wiping my conda virtual env and restarting doing:
> 
> ```
> # create a new environment
> conda create -n visgpt python=3.8
> 
> # activate the new environment
> conda activate visgpt
> 
> #  prepare the basic environments
> conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
> pip install -r requirement.txt  # Edited to comment out the first two lines with torch & torchvision, may or may not be necessary
> 
> # download the visual foundation models
> bash download.sh
> 
> # prepare your private openAI private key
> export OPENAI_API_KEY={Your_Private_Openai_Key}
> 
> # create a folder to save images
> mkdir ./image
> 
> # Start Visual ChatGPT !
> python visual_chatgpt.py
> ```

Following these steps fixed the error for me.
