### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by andzejsp** [microsoft/visual-chatgpt#43]
GPU: Quadro P2200

Steps i took to run it on windows:

Install miniconda:
https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe

Do not add to PATH, leave everything as default, just press next untill it installs.

Created installation.cmd file as such:

```
echo off
:: create a new environment
Echo "Run conda"
call C:\Users\<USERNAME>\miniconda3\Scripts\activate.bat 


Echo "Create env"
call conda create -p visgpt python=3.8

:: activate the new environment
Echo "Activate env"
call conda activate ./visgpt

:: install pytorch and cuda
Echo "install pytorch and cuda"

call conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

::  prepare the basic environments
Echo "Pip Install req"
call pip install -r requirement.txt

:: clone controlnet repo
IF EXIST "ControlNet/" (
  Echo "ControlNet/ exist"
) ELSE (
Echo "Git clone https://github.com/lllyasviel/ControlNet.git"
call git clone https://github.com/lllyasviel/ControlNet.git

echo "Create symlinks"
call mklink /J "./ldm" "./ControlNet/ldm"
call mklink /J "./cldm" "./ControlNet/cldm"
call mklink /J "./annotator" "./ControlNet/annotator"
)

:: download the visual foundation models

Echo "Download models (Large files 8 models in total)"

cd ControlNet/models

IF NOT EXIST "control_sd15_canny.pth" (
echo "downloading model control_sd15_canny.pth"
 python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_canny.pth
) 
IF NOT EXIST "control_sd15_depth.pth" (
echo "downloading model control_sd15_depth.pth"
python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_depth.pth
)
IF NOT EXIST "control_sd15_hed.pth" (
echo "downloading model control_sd15_hed.pth"
python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_hed.pth
)
IF NOT EXIST "control_sd15_mlsd.pth" (
echo "downloading model control_sd15_mlsd.pth"
python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_mlsd.pth
)
IF NOT EXIST "control_sd15_normal.pth" (
echo "downloading model control_sd15_normal.pth"
python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_normal.pth
)
IF NOT EXIST "control_sd15_openpose.pth" (
echo "downloading model control_sd15_openpose.pth"
python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_openpose.pth
)
IF NOT EXIST "control_sd15_scribble.pth" (
echo "downloading model control_sd15_scribble.pth"
python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_scribble.pth
)
IF NOT EXIST "control_sd15_seg.pth" (
echo "downloading model control_sd15_seg.pth"
python -m wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_seg.pth
)

cd ../../

:: prepare your private openAI private key
set OPENAI_API_KEY=<YOUR API KEY>

:: create a folder to save images
mkdir image

:: Start Visual ChatGPT !
python visual_chatgpt.py

pause
```

Somewhat automated installation script, adopted from the Readme.md file.

During trials i have noticed some requirements were missing, so i added them to `requirement.txt`

```
wget
chardet
cchardet
```

The problem is that after it tries to launch the `python visual_chatgpt.py` i get the error.

```
...
"Download models (Large files 8 models in total)"
A subdirectory or file image already exists.
No CUDA runtime is found, using CUDA_HOME='E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt'
Initializing VisualChatGPT
Initializing StableDiffusionInpaint to cuda:6
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visual_chatgpt.py:940 in <module>                             │
│                                                                                                  │
│   937 │   │   return state, state, txt + ' ' + image_filename + ' '                              │
│   938                                                                                            │
│   939 if __name__ == '__main__':                                                                 │
│ ❱ 940 │   bot = ConversationBot()                                                                │
│   941 │   with gr.Blocks(css="#chatbot .overflow-y-auto{height:500px}") as demo:                 │
│   942 │   │   chatbot = gr.Chatbot(elem_id="chatbot", label="Visual ChatGPT")                    │
│   943 │   │   state = gr.State([])                                                               │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visual_chatgpt.py:804 in __init__                             │
│                                                                                                  │
│   801 │   def __init__(self):                                                                    │
│   802 │   │   print("Initializing VisualChatGPT")                                                │
│   803 │   │   self.llm = OpenAI(temperature=0)                                                   │
│ ❱ 804 │   │   self.edit = ImageEditing(device="cuda:6")                                          │
│   805 │   │   self.i2t = ImageCaptioning(device="cuda:4")                                        │
│   806 │   │   self.t2i = T2I(device="cuda:1")                                                    │
│   807 │   │   self.image2canny = image2canny()                                                   │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visual_chatgpt.py:151 in __init__                             │
│                                                                                                  │
│   148 │   def __init__(self, device):                                                            │
│   149 │   │   print("Initializing StableDiffusionInpaint to %s" % device)                        │
│   150 │   │   self.device = device                                                               │
│ ❱ 151 │   │   self.mask_former = MaskFormer(device=self.device)                                  │
│   152 │   │   self.inpainting = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stabl   │
│   153 │                                                                                          │
│   154 │   def remove_part_of_image(self, input):                                                 │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visual_chatgpt.py:123 in __init__                             │
│                                                                                                  │
│   120 │   def __init__(self, device):                                                            │
│   121 │   │   self.device = device                                                               │
│   122 │   │   self.processor = CLIPSegProcessor.from_pretrained("CIDAS/clipseg-rd64-refined")    │
│ ❱ 123 │   │   self.model = CLIPSegForImageSegmentation.from_pretrained("CIDAS/clipseg-rd64-ref   │
│   124 │                                                                                          │
│   125 │   def inference(self, image_path, text):                                                 │
│   126 │   │   threshold = 0.5                                                                    │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\transformers\modeling_utils.py:1749  │
│ in to                                                                                            │
│                                                                                                  │
│   1746 │   │   │   │   " model has already been set to the correct devices and casted to the co  │
│   1747 │   │   │   )                                                                             │
│   1748 │   │   else:                                                                             │
│ ❱ 1749 │   │   │   return super().to(*args, **kwargs)                                            │
│   1750 │                                                                                         │
│   1751 │   def half(self, *args):                                                                │
│   1752 │   │   # Checks if the model has been loaded in 8-bit                                    │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\nn\modules\module.py:927 in to │
│                                                                                                  │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│    925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│    926 │   │                                                                                     │
│ ❱  927 │   │   return self._apply(convert)                                                       │
│    928 │                                                                                         │
│    929 │   def register_backward_hook(                                                           │
│    930 │   │   self, hook: Callable[['Module', _grad_t, _grad_t], Union[None, Tensor]]           │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in    │
│ _apply                                                                                           │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in    │
│ _apply                                                                                           │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in    │
│ _apply                                                                                           │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in    │
│ _apply                                                                                           │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\nn\modules\module.py:602 in    │
│ _apply                                                                                           │
│                                                                                                  │
│    599 │   │   │   # track autograd history of `param_applied`, so we have to use                │
│    600 │   │   │   # `with torch.no_grad():`                                                     │
│    601 │   │   │   with torch.no_grad():                                                         │
│ ❱  602 │   │   │   │   param_applied = fn(param)                                                 │
│    603 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)       │
│    604 │   │   │   if should_use_set_data:                                                       │
│    605 │   │   │   │   param.data = param_applied                                                │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\nn\modules\module.py:925 in    │
│ convert                                                                                          │
│                                                                                                  │
│    922 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):                       │
│    923 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() els  │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│ ❱  925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│    926 │   │                                                                                     │
│    927 │   │   return self._apply(convert)                                                       │
│    928                                                                                           │
│                                                                                                  │
│ E:\VBA_PROJECTS\Git\visual-chatpgt\visgpt\lib\site-packages\torch\cuda\__init__.py:211 in        │
│ _lazy_init                                                                                       │
│                                                                                                  │
│   208 │   │   │   │   "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "        │
│   209 │   │   │   │   "multiprocessing, you must use the 'spawn' start method")                  │
│   210 │   │   if not hasattr(torch._C, '_cuda_getDeviceCount'):                                  │
│ ❱ 211 │   │   │   raise AssertionError("Torch not compiled with CUDA enabled")                   │
│   212 │   │   if _cudart is None:                                                                │
│   213 │   │   │   raise AssertionError(                                                          │
│   214 │   │   │   │   "libcudart functions unavailable. It looks like you have a broken build?   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Torch not compiled with CUDA enabled
Press any key to continue . . .
```

Maybe i need different cuda/torch version given i have such old GPU? Im not smart, i just want to play with this to see whats good.

**Comment by gillopillo** [comment]
same problem. If anyone can get it running on linux, I would love to hear how.

**Comment by windhamwong** [comment]
Try this
```pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113```

**Comment by adormire** [comment]
I am having this exact same problem on macOS Ventura 13.2.1.

**Comment by andzejsp** [comment]
> Try this `pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113`

Hi, i came home to try it out on RTX3090 but now it gives me this error:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ J:\LocalRepos\visual-chatgpt\visual_chatgpt.py:940 in <module>                                   │
│                                                                                                  │
│   937 │   │   return state, state, txt + ' ' + image_filename + ' '                              │
│   938                                                                                            │
│   939 if __name__ == '__main__':                                                                 │
│ ❱ 940 │   bot = ConversationBot()                                                                │
│   941 │   with gr.Blocks(css="#chatbot .overflow-y-auto{height:500px}") as demo:                 │
│   942 │   │   chatbot = gr.Chatbot(elem_id="chatbot", label="Visual ChatGPT")                    │
│   943 │   │   state = gr.State([])                                                               │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visual_chatgpt.py:804 in __init__                                   │
│                                                                                                  │
│   801 │   def __init__(self):                                                                    │
│   802 │   │   print("Initializing VisualChatGPT")                                                │
│   803 │   │   self.llm = OpenAI(temperature=0)                                                   │
│ ❱ 804 │   │   self.edit = ImageEditing(device="cuda:6")                                          │
│   805 │   │   self.i2t = ImageCaptioning(device="cuda:4")                                        │
│   806 │   │   self.t2i = T2I(device="cuda:1")                                                    │
│   807 │   │   self.image2canny = image2canny()                                                   │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visual_chatgpt.py:151 in __init__                                   │
│                                                                                                  │
│   148 │   def __init__(self, device):                                                            │
│   149 │   │   print("Initializing StableDiffusionInpaint to %s" % device)                        │
│   150 │   │   self.device = device                                                               │
│ ❱ 151 │   │   self.mask_former = MaskFormer(device=self.device)                                  │
│   152 │   │   self.inpainting = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stabl   │
│   153 │                                                                                          │
│   154 │   def remove_part_of_image(self, input):                                                 │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visual_chatgpt.py:123 in __init__                                   │
│                                                                                                  │
│   120 │   def __init__(self, device):                                                            │
│   121 │   │   self.device = device                                                               │
│   122 │   │   self.processor = CLIPSegProcessor.from_pretrained("CIDAS/clipseg-rd64-refined")    │
│ ❱ 123 │   │   self.model = CLIPSegForImageSegmentation.from_pretrained("CIDAS/clipseg-rd64-ref   │
│   124 │                                                                                          │
│   125 │   def inference(self, image_path, text):                                                 │
│   126 │   │   threshold = 0.5                                                                    │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\transformers\modeling_utils.py:1749 in to  │
│                                                                                                  │
│   1746 │   │   │   │   " model has already been set to the correct devices and casted to the co  │
│   1747 │   │   │   )                                                                             │
│   1748 │   │   else:                                                                             │
│ ❱ 1749 │   │   │   return super().to(*args, **kwargs)                                            │
│   1750 │                                                                                         │
│   1751 │   def half(self, *args):                                                                │
│   1752 │   │   # Checks if the model has been loaded in 8-bit                                    │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\torch\nn\modules\module.py:927 in to       │
│                                                                                                  │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│    925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│    926 │   │                                                                                     │
│ ❱  927 │   │   return self._apply(convert)                                                       │
│    928 │                                                                                         │
│    929 │   def register_backward_hook(                                                           │
│    930 │   │   self, hook: Callable[['Module', _grad_t, _grad_t], Union[None, Tensor]]           │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in _apply   │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in _apply   │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in _apply   │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\torch\nn\modules\module.py:579 in _apply   │
│                                                                                                  │
│    576 │                                                                                         │
│    577 │   def _apply(self, fn):                                                                 │
│    578 │   │   for module in self.children():                                                    │
│ ❱  579 │   │   │   module._apply(fn)                                                             │
│    580 │   │                                                                                     │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\torch\nn\modules\module.py:602 in _apply   │
│                                                                                                  │
│    599 │   │   │   # track autograd history of `param_applied`, so we have to use                │
│    600 │   │   │   # `with torch.no_grad():`                                                     │
│    601 │   │   │   with torch.no_grad():                                                         │
│ ❱  602 │   │   │   │   param_applied = fn(param)                                                 │
│    603 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)       │
│    604 │   │   │   if should_use_set_data:                                                       │
│    605 │   │   │   │   param.data = param_applied                                                │
│                                                                                                  │
│ J:\LocalRepos\visual-chatgpt\visgpt\lib\site-packages\torch\nn\modules\module.py:925 in convert  │
│                                                                                                  │
│    922 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):                       │
│    923 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() els  │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│ ❱  925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│    926 │   │                                                                                     │
│    927 │   │   return self._apply(convert)                                                       │
│    928                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Press any key to continue . . .
```

**Comment by b2zer** [comment]
@andzejsp - see here for an easy fix: https://github.com/microsoft/visual-chatgpt/issues/7

**Comment by andzejsp** [comment]
> @andzejsp - see here for an easy fix: #7

thanks, worked, but now how do i know which tools to turn off because i have limited V ram?

## GPU memory usage
Here we list the GPU memory usage of each visual foundation model, one can modify ``self.tools`` with fewer visual foundation models to save your GPU memory:

| Foundation Model        | Memory Usage (MB) |
|------------------------|-------------------|
| ImageEditing           | 6667              |
| ImageCaption           | 1755              |
| T2I                    | 6677              |
| canny2image            | 5540              |
| line2image             | 6679              |
| hed2image              | 6679              |
| scribble2image         | 6679              |
| pose2image             | 6681              |
| BLIPVQA                | 2709              |
| seg2image              | 5540              |
| depth2image            | 6677              |
| normal2image           | 3974              |
| InstructPix2Pix        | 2795              |

**Comment by b2zer** [comment]
I found this to be a very useful fork: 
https://github.com/rupeshs/visual-chatgpt/tree/add-colab-support

You can just grab the visual_chatgpt.py from there (that's what I did) and use that, then edit the code at the bottom near where you already edited it, removing the comments # one by one until it gets too crowded in your VRAM.

Hint: The stuff the author has commented out may still read "cuda:3" or whatever, so best to make all of that "cuda:0" again in case you later decide to include it. :-)

**Comment by b2zer** [comment]
My personal choice was to definitely include instruct-pix2pix as well (and I am still having a weird error on ControlNet in this implementation, but I have used it with AUTOMATIC1111's gradio interface, running local - hence why the error here is weird), and I found "canny" and "hed" as well as "depth" and maybe also "scribbe" to be most useful.

**Comment by Outsiderj** [comment]
> @andzejsp - see here for an easy fix: #7

You're my hero, thanks!  Spent all day banging my head on this error yesterday for Animated diffusion, this fixed it!

**Comment by andzejsp** [comment]
> > @andzejsp - see here for an easy fix: #7
> 
> You're my hero, thanks!  Spent all day banging my head on this error yesterday for Animated diffusion, this fixed it!
> 

Can u point me to animate diffusion? Where can i get it?

**Comment by Outsiderj** [comment]
https://github.com/guoyww/animatediff/

Also a google colab here - https://colab.research.google.com/drive/17IBbG6aQfipvsLWT8KasJt_lWFMDHqHB
