### ISSUE TITLE
Runtime error CUDA: invalid device ordinal

### ISSUE THREAD

**Issue by imJunaidAfzal** [microsoft/visual-chatgpt#7]
Hi! i'm trying to run this but got this error:
I follow the same process mention in readme.
```
Initializing VisualChatGPT
Initializing StableDiffusionInpaint to cuda:6
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/visual_chatgpt.py:945 in <module>                                   │
│                                                                              │
│   942 if __name__ == '__main__':                                             │
│   943 │   bot = ConversationBot()                                            │
│   944 │   with gr.Blocks(css="#chatbot .overflow-y-auto{height:500px}") as d │
│ ❱ 945 │   │   chatbot = gr.Chatbot(elem_id="chatbot", label="Visual ChatGPT" │
│   946 │   │   state = gr.State([])                                           │
│   947 │   │   with gr.Row():                                                 │
│   948 │   │   │   with gr.Column(scale=0.7):                                 │
│                                                                              │
│ /content/visual_chatgpt.py:809 in __init__                                   │
│                                                                              │
│   806 │   │   self.llm = OpenAI(temperature=0, openai_api_key=KEY │
│   807 │   │   self.edit = ImageEditing(device="cuda:6")                      │
│   808 │   │   self.i2t = ImageCaptioning(device="cuda:4")                    │
│ ❱ 809 │   │   self.t2i = T2I(device="cuda:1")                                │
│   810 │   │   self.image2canny = image2canny()                               │
│   811 │   │   self.canny2image = canny2image(device="cuda:1")                │
│   812 │   │   self.image2line = image2line()                                 │
│                                                                              │
│ /content/visual_chatgpt.py:156 in __init__                                   │
│                                                                              │
│   153 │   │   self.device = device                                           │
│   154 │   │   self.mask_former = MaskFormer(device=self.device)              │
│   155 │   │   self.inpainting = StableDiffusionInpaintPipeline.from_pretrain │
│ ❱ 156 │                                                                      │
│   157 │   def remove_part_of_image(self, input):                             │
│   158 │   │   image_path, to_be_removed_txt = input.split(",")               │
│   159 │   │   print(f'remove_part_of_image: to_be_removed {to_be_removed_txt │
│                                                                              │
│ /content/visual_chatgpt.py:128 in __init__                                   │
│                                                                              │
│   125 │   │   self.processor = CLIPSegProcessor.from_pretrained("CIDAS/clips │
│   126 │   │   self.model = CLIPSegForImageSegmentation.from_pretrained("CIDA │
│   127 │                                                                      │
│ ❱ 128 │   def inference(self, image_path, text):                             │
│   129 │   │   threshold = 0.5                                                │
│   130 │   │   min_area = 0.02                                                │
│   131 │   │   padding = 20                                                   │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/transformers/modeling_utils.py:1749   │
│ in to                                                                        │
│                                                                              │
│   1746 │   │   │   │   " model has already been set to the correct devices a │
│   1747 │   │   │   )                                                         │
│   1748 │   │   else:                                                         │
│ ❱ 1749 │   │   │   return super().to(*args, **kwargs)                        │
│   1750 │                                                                     │
│   1751 │   def half(self, *args):                                            │
│   1752 │   │   # Checks if the model has been loaded in 8-bit                │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:927 in to  │
│                                                                              │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_fo │
│    925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.i │
│    926 │   │                                                                 │
│ ❱  927 │   │   return self._apply(convert)                                   │
│    928 │                                                                     │
│    929 │   def register_backward_hook(                                       │
│    930 │   │   self, hook: Callable[['Module', _grad_t, _grad_t], Union[None │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in     │
│ _apply                                                                       │
│                                                                              │
│    576 │                                                                     │
│    577 │   def _apply(self, fn):                                             │
│    578 │   │   for module in self.children():                                │
│ ❱  579 │   │   │   module._apply(fn)                                         │
│    580 │   │                                                                 │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in     │
│ _apply                                                                       │
│                                                                              │
│    576 │                                                                     │
│    577 │   def _apply(self, fn):                                             │
│    578 │   │   for module in self.children():                                │
│ ❱  579 │   │   │   module._apply(fn)                                         │
│    580 │   │                                                                 │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in     │
│ _apply                                                                       │
│                                                                              │
│    576 │                                                                     │
│    577 │   def _apply(self, fn):                                             │
│    578 │   │   for module in self.children():                                │
│ ❱  579 │   │   │   module._apply(fn)                                         │
│    580 │   │                                                                 │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:579 in     │
│ _apply                                                                       │
│                                                                              │
│    576 │                                                                     │
│    577 │   def _apply(self, fn):                                             │
│    578 │   │   for module in self.children():                                │
│ ❱  579 │   │   │   module._apply(fn)                                         │
│    580 │   │                                                                 │
│    581 │   │   def compute_should_use_set_data(tensor, tensor_applied):      │
│    582 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:602 in     │
│ _apply                                                                       │
│                                                                              │
│    599 │   │   │   # track autograd history of `param_applied`, so we have t │
│    600 │   │   │   # `with torch.no_grad():`                                 │
│    601 │   │   │   with torch.no_grad():                                     │
│ ❱  602 │   │   │   │   param_applied = fn(param)                             │
│    603 │   │   │   should_use_set_data = compute_should_use_set_data(param,  │
│    604 │   │   │   if should_use_set_data:                                   │
│    605 │   │   │   │   param.data = param_applied                            │
│                                                                              │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:925 in     │
│ convert                                                                      │
│                                                                              │
│    922 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):   │
│    923 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or │
│    924 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_fo │
│ ❱  925 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.i │
│    926 │   │                                                                 │
│    927 │   │   return self._apply(convert)                                   │
│    928                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so 
the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by b2zer** [comment]
That's actually because it tries to load the models to eight cuda devices (cuda 0 to cuda 7). If you're like me and trying to running it on a lousy single GPU, edit visual_chatgpt.py by finding "cuda", and replace all of them to read "cuda:0". 

Note: I ran into another issue for now, which is why I came looking here, but until that happens [RuntimeError: Error(s) in loading state_dict for ControlLDM: Unexpected key(s) in state_dict: "logvar"] - the models DO load after this fix (requiring some 10 GB VRAM maybe, until the RunTimeError happens]. Good luck!

**Comment by imJunaidAfzal** [comment]
@b2zer Thanks for the help.

**Comment by powderblock** [comment]
> That's actually because it tries to load the models to eight cuda devices (cuda 0 to cuda 7). If you're like me and trying to running it on a lousy single GPU, edit visual_chatgpt.py by finding "cuda", and replace all of them to read "cuda:0".
> 
> Note: I ran into another issue for now, which is why I came looking here, but until that happens [RuntimeError: Error(s) in loading state_dict for ControlLDM: Unexpected key(s) in state_dict: "logvar"] - the models DO load after this fix (requiring some 10 GB VRAM maybe, until the RunTimeError happens]. Good luck!

Fixed the issue for me! Thank you

**Comment by gavi** [comment]
Thanks - This fixes the issue
